### ISSUE TITLE
How is it compatible with larger displays?

### ISSUE THREAD

**Issue by Ckrty** [NordicPlayground/nrf-esl-bluetooth#2]
Hi,
I see that the [documentation](https://pirun.github.io/nrf-esl-bluetooth_docs/esl_tag.html#peripheral-esl) describes support for 2.13inch displays. 
Unfortunately, I only have a 5.83inch display on hand!
The display is an electronic paper display with three colors, 648x480 pixels.
That is, a full three-color image has a size of (648*480/8)*2 = 77,760Bytes.
If I specify CONFIG_ESL_IMAGE_BUFFER_SIZE as 77760, I get a RAM overflow error!
Please consider providing solutions for this, thanks!

By the way, is the nRF52833 the minimum requirement for a complete ESL device, and is it possible to implement a display-only ESL on the nRF52832?

**Comment by pirun** [comment]
Thanks for your opinion.
> Hi, I see that the [documentation](https://pirun.github.io/nrf-esl-bluetooth_docs/esl_tag.html#peripheral-esl) describes support for 2.13inch displays. Unfortunately, I only have a 5.83inch display on hand! The display is an electronic paper display with three colors, 648x480 pixels. That is, a full three-color image has a size of (648*480/8)*2 = 77,760Bytes. If I specify CONFIG_ESL_IMAGE_BUFFER_SIZE as 77760, I get a RAM overflow error! Please consider providing solutions for this, thanks!

AFAIK, there is no existed support for three color EPD driver in Zephyr now.
You can consider splitting it into 2 images (just as EPD manufacturer mention in spec) if you are working on your own EPD driver.
There is a WIP about replacing storage backend to achieve small chunk of buffer for bigger display. 
> 
> By the way, is the nRF52833 the minimum requirement for a complete ESL device, and is it possible to implement a display-only ESL on the nRF52832?
By disabling debug feature , you might use 832 with small display to implement ESL.

Please contact your local RSM to acquire tech support.

**Comment by pirun** [comment]
Answered offline.
